codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "88...100"

  status:
    project:
      default:
        threshold: 5%

    patch:
      default:
        threshold: 10%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

