:page-layout: getting-started
:page-title: Using other reactive programming libraries
:page-description: Learn how to integrate Mutiny with RX Java or Reactor
:page-previous: Collecting items from Multi
:page-previous-href: /getting-started/collecting-items
:page-next: From reactive to imperative
:page-next-href: /getting-started/reactive-to-imperative
:page-liquid:

== Integrating others reactive libraries

You may need to integrate libraries exposing an API using other reactive programming libraries such as RX Java or Reactor.
Mutiny has a built-in conversion mechanism to ease that integration.

=== Picking the right dependency

The conversions are implemented in different artifacts:

[source, xml]
----
<!-- Mutiny <-> Reactor -->
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>mutiny-reactor</artifactId>
  <version>{{ site.data.versions.mutiny_version }}</version>
</dependency>

<!-- Mutiny <-> RX Java -->
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>mutiny-rxjava</artifactId>
  <version>{{ site.data.versions.mutiny_version }}</version>
</dependency>
----

=== Integration with Project Reactor

Project Reactor is a popular reactive programming library.
It offers two types: `Mono` and `Flux,` both implementing Reactive Stream `Publisher`.

To use the Reactor <-> Mutiny converter, add the following imports to your class:


[source, java]
----
import io.smallrye.mutiny.converters.multi.MultiReactorConverters;
import io.smallrye.mutiny.converters.uni.UniReactorConverters;
----

==== Converting a Flux or a Mono into a Multi

Both `Flux` and `Mono` implement `Publisher` so the conversion is based on the Reactive Streams interoperability:

[source, java]
----
Multi<T> multiFromFlux = Multi.createFrom().publisher(flux);
Multi<T> multiFromMono = Multi.createFrom().publisher(mono);
----

==== Converting a Flux or a Mono into a Uni

As you can create `Uni` from a `Publisher` the same approach can be used to create `Uni` instances:

[source, java]
----
Uni<T> uniFromFlux = Uni.createFrom().publisher(flux);
Uni<T> uniFromMono = Uni.createFrom().publisher(mono);
----

If the `Flux` or `Mono` sends the _completion_ event before an item event (because it's empty), the `Uni` emits a `null` item.
For `Flux,` the `Uni` emits the first item and cancels the `Flux` subscription after that emission.

==== Converting a Multi into a Flux or Mono

As for the opposite direction, the conversion relies on Reactive Streams:

[source, java]
----
Flux<T> flux = Flux.from(multi);
Mono<T> mono = Mono.from(multi);
----

==== Converting a Uni into a Flux or Mono

Converting a `Uni` into a `Flux` or a `Mono` requires a converter:

[source, java]
----
Mono<T> mono = uni.convert().with(UniReactorConverters.toMono());
Flux<T> flux = uni.convert().with(UniReactorConverters.toFlux());
----

If the `Uni` emits `null`, it sends the _completion_ event.

=== Integration with RX Java

RxJava is another reactive programming library.
It offers 5 types: `Completable` (no item), `Single` (one item), `Maybe` (0 or 1 item), `Observable` (multiple items), `Flowable` (multiple items, implements Reactive Stream `Publisher`).

To use the RxJava <-> Mutiny converter, add the following imports to your class:

[source, java]
----
import io.smallrye.mutiny.converters.multi.MultiRxConverters;
import io.smallrye.mutiny.converters.uni.UniRxConverters;
----

==== Converting an Observable or a Flowable into a Multi

Both `Observable` and `Flowable` are item streams.
However, `Observable` does not implement `Publisher` and so does not have back-pressure support.

To create `Multi` from an `Observable,` you need a specific converter:

[source, java]
----
Multi<T> multiFromObservable = Multi.createFrom().converter(
  MultiRxConverters.fromObservable(), observable);
----

Converting a `Flowable` is easier as it's a `Publisher`:

[source, java]
----
Multi<T> multi = Multi.createFrom().publisher(flowable);
----

==== Converting a Completable, Single or Maybe into a Multi

To create a `Multi` from a `Completable,` `Single` or `Maybe` you need a specific converter:

[source, java]
----
Multi<Void> multiFromCompletable = Multi.createFrom()
  .converter(MultiRxConverters.fromCompletable(), completable);

Multi<T> multiFromSingle = Multi.createFrom().converter(MultiRxConverters.fromSingle(), single);

Multi<T> multiFromMaybe = Multi.createFrom().converter(MultiRxConverters.fromMaybe(), maybe);
----

* Creating a `Multi` from a `Completable` always produces a `Multi<Void>` that only emits the _completion_ or _failure_ event.
* Creating a `Multi` from a `Single` produces a `Multi` that emits the item and then completes it.
* Creating a `Multi` from a `Maybe` produces a `Multi` that emits the item (if any) and then completes it.
  If the `Maybe` is empty, then the created `Multi` emits the _completion_ event.

When `Completable,` `Single,` or `Maybe` emit a failure, then that failure is emitted by the created `Multi`.

==== Converting an Observable or a Flowable into a Uni

To create a `Uni` from an `Observable,` you need to use a specific converter:

[source, java]
----
Uni<T> uniFromObservable = Uni.createFrom().converter(UniRxConverters.fromObservable(), observable);
----

The creation from a `Flowable` can be done using the Reactive Streams interoperability:

[source, java]
----
Uni<T> uniFromFlowable = Uni.createFrom().publisher(flowable);
----

In both cases, it cancels the subscription to the `Flowable` or `Observable` after receiving the first item.
If the `Flowable` or `Observable` completes without items, the `Uni` emits a `null` item.

==== Converting a Completable, Single or Maybe into a Uni

To create a `Uni` from a `Completable,` `Single,` or `Maybe`, you need to use a specific converter:

[source, java]
----
Uni<Void> uniFromCompletable = Uni.createFrom().converter(UniRxConverters.fromCompletable(), completable);

Uni<T> uniFromSingle = Uni.createFrom().converter(UniRxConverters.fromSingle(), single);

Uni<T> uniFromMaybe = Uni.createFrom().converter(UniRxConverters.fromMaybe(), maybe);
----

Converting a `Completable` to a `Uni` always produces a `Uni<Void>,` that emits either `null` once the `Completable` completes or the failure if it fails.
The `Maybe` to `Uni` conversion emits a `null` item if the `Maybe` completes without an item.

==== Converting a Multi into a RX Java objects

The conversion from a `Multi` to the various RX Java objects is done using converters:

[source, java]
----
Completable completable = multi.convert().with(MultiRxConverters.toCompletable());

Single<Optional<T>> single = multi.convert().with(MultiRxConverters.toSingle());

Single<T> single2 = multi.convert().with(MultiRxConverters
  .toSingle().onEmptyThrow(() -> new Exception("D'oh!")));

Maybe<T> maybe = multi.convert().with(MultiRxConverters.toMaybe());

Observable<T> observable = multi.convert().with(MultiRxConverters.toObservable());

Flowable<T> flowable = multi.convert().with(MultiRxConverters.toFlowable());
----

The creation of a `Completable` from a `Multi` discards all the items emitted by the `Multi`.
It forwards the _completion_ or _failure_ event.

Converting a `Multi` into a `Single` returns a `Single<Optional<T>>,` as the `Multi` may complete without items.
You can also produce a `Single<T>` and emit a _failure_ event if the `Multi` completes without items.
Configure the failure to be forwarded using `onEmptyThrow.`

TIP: You can also create a `Flowable` from a `Multi` using: `Flowable.fromPublisher(multi)`.

==== Converting a Uni into a RX Java type

Similarly to the conversion from a `Multi` into an RX Type, converting a `Uni` requires a converter:

[source, java]
----
Completable completable = uni.convert().with(UniRxConverters.toCompletable());

Single<Optional<String>> single = uni.convert().with(UniRxConverters.toSingle());

Single<String> single2 = uni.convert().with(UniRxConverters.toSingle().failOnNull());

Maybe<String> maybe = uni.convert().with(UniRxConverters.toMaybe());

Observable<String> observable = uni.convert().with(UniRxConverters.toObservable());

Flowable<String> flowable = uni.convert().with(UniRxConverters.toFlowable());
----

The creation of a `Completable` from a `Uni` discards the item and sends the _completion_ signal after emission.

Converting a `Uni` into a `Single` returns a `Single<Optional<T>>,` as the `Uni` may emit `null.`
You can also produce a `Single<T>` and emits a _failure_ event if the `Uni` sends `null.`
Configures the failure to forward using `failOnNull.`

The creation of a `Maybe,` `Flowable,` or an `Observable` from a `Uni` produces an empty `Maybe,` `Flowable,` or `Observable` if the `Uni` emits `null.`
For `Flowable` and `Observable,` if the `Uni` emits a _non-null_ item, that item is emitted, followed immediately by the _completion_ signal.

