:page-layout: getting-started
:page-guide-id: download
:page-liquid: 

[[dependency]]
== Using Mutiny in a Java application

Add the _dependency_ to your project:

.https://maven.apache.org/[Maven]
[source, xml]
----
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>mutiny</artifactId>
  <version>{{ site.data.versions.mutiny_version }}</version>
</dependency>
----

.https://gradle.org/[Gradle with Groovy]
[source, text]
----
implementation 'io.smallrye.reactive:mutiny:{{ site.data.versions.mutiny_version }}'
----

.https://gradle.org/[Gradle with Kotlin]
[source, kotlin]
----
implementation("io.smallrye.reactive:mutiny:{{ site.data.versions.mutiny_version }}")
----

.https://github.com/jbangdev/jbang[JBang]
[source, java]
----
//DEPS io.smallrye.reactive:mutiny:{{ site.data.versions.mutiny_version }}
----

[[quarkus]]
=== Using Mutiny with Quarkus

Most of the https://quarkus.io[Quarkus] extensions with reactive capabilities already depend on Mutiny.
You can also add the `quarkus-mutiny` dependency explicitly:

[source, bash]
----
mvn quarkus:add-extension -Dextensions=mutiny
----

Or directly add the dependency to your `pom.xml`

[source, xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-mutiny</artifactId>
</dependency>
----

Follow the https://quarkus.io/guides/getting-started-reactive[Getting started with reactive] guide for more details.


[[bom]]
=== Using the Mutiny BOM

Mutiny provides a https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms[BOM] to avoid having to declare the version of each module you depend on.

In Maven, use it as follows:

[source, xml]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.smallrye.reactive</groupId>
            <artifactId>mutiny-bom</artifactId>
            <version>{{ site.data.versions.mutiny_version }}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>io.smallrye.reactive</groupId>
        <artifactId>mutiny</artifactId>
    </dependency>
</dependencies>
----

In Gradle, add:

[source, kotlin]
----
dependencies {
  implementation platform("io.smallrye.reactive:mutiny-bom:{{ site.data.versions.mutiny_version }}")
  implementation("io.smallrye.reactive:mutiny")
}
----

[[vertx]]
== Using Mutiny with Eclipse Vert.x

API bindings for many popular modules and clients from the https://vertx.io[Vert.x] stack are available from the https://smallrye.io/smallrye-mutiny-vertx-bindings[Smallrye Mutiny Vert.x Bindings project].

Here is how to add a dependency to the Vert.x core library with Mutiny bindings:

[source, xml]
----
<dependency>
  <groupId>io.smallrye.reactive</groupId>
  <artifactId>smallrye-mutiny-vertx-core</artifactId>
  <version>{{ site.data.versions.vertx_mutiny_clients }}</version>
</dependency>
----

See https://smallrye.io/smallrye-mutiny-vertx-bindings[https://smallrye.io/smallrye-mutiny-vertx-bindings] for the complete documentation and instructions.


[[download]]
== Direct Download

You can also download the Mutiny JARs directly from https://search.maven.org/search?q=g:io.smallrye.reactive%20AND%20a:mutiny*%20AND%20v:{{ site.data.versions.mutiny_version }}[Maven Central].