:page-layout: guides
:page-guide-id: infrastructure
:page-liquid:
:page-show-toc: false
:include_dir: ../../../../src/test/java/guides/infrastructure

Sometimes, Mutiny needs to execute tasks on other threads, such as monitoring time or delaying actions.
Most operators relying on such capacity let you pass either a `ScheduledExecutorService` or an `ExecutorService`.

Mutiny uses the https://www.oracle.com/technical-resources/articles/java/fork-join.html[fork-join] pool as default executor.
A `ScheduledExecutorService` is also created but delegates the execution of the delayed/scheduled tasks to the default executor.

In the case you want to integrate Mutiny with a thread pool managed by a platform, you can configure it using `Infrastructure.setDefaultExecutor()` method:

[source, java, indent=0]
----
include::{include_dir}/InfrastructureTest.java[tag=infra]
----

You can configure the default executor using the `Infrastructure.setDefaultExecutor` method:

[source, java, indent=0]
----
include::{include_dir}/InfrastructureTest.java[tag=set-infra]
----

TIP: If you are using Quarkus, the default executor is already configured to use the Quarkus worker thread pool.