:page-layout: guides
:page-guide-id: rx
:page-liquid:
:page-show-toc: false
:include_dir: ../../../../src/test/java/guides/

If you are a seasoned reactive developer, you may miss the `map`, `flatMap`, `concatMap` methods.
Mutiny API is quite different from the _ standard_ reactive eXtensions API.
There are multiple reasons for this choice.
Typically, _flatMap_ is not necessarily well understood by every developer, leading to potentially catastrophic consequences.

That being said, Mutiny provides the _map_, _flatMap_ and _concatMap_ methods, implementing the most common variant for each:

[source,java,indent=0]
----
include::{include_dir}RxTest.java[tags=rx]
----

The Mutiny equivalents are:

* `map` -> `onItem().transform()`
* `flatMap` -> `onItem().transformToUniAndMerge` and `onItem().transformToMultiAndMerge`
* `concatMap` -> `onItem().transformToUniAndConcatenate` and `onItem().transformToMultiAndConcatenate`

The following snippet demonstrates how to uses these methods:

[source,java,indent=0]
----
include::{include_dir}RxTest.java[tags=mutiny]
----
