== How Do I do x?

=== How do I transform items?

To transform items synchronously use the `apply` operators:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToTransformTest.java[tags=sync]
----

You can also transform items asynchronously using the `produceUni` / `produceCompletionStage` operators:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToTransformTest.java[tags=async]
----

If you need to generate a sequence of items use, `producePublisher`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToTransformTest.java[tags=multi]
----

=== How do I filter/select items?

On `Multi`, you may need to filter / select items.
To achieve this, there is a set of methods available in `multi.transform()`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToFilterTest.java[tags=filter]

include::../../../src/test/java/snippets/HowToFilterTest.java[tags=take]

include::../../../src/test/java/snippets/HowToFilterTest.java[tags=skip]

----

You can also drop distinct items or drop repetitions:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToFilterTest.java[tags=distinct]

include::../../../src/test/java/snippets/HowToFilterTest.java[tags=repetition]
----

=== Where are my map, flatMap and concatMap?

If you are a seasoned reactive developer, you may miss the infamous `map`, `flatMap`, `concatMap` methods.
Mutiny also proposes there methods using the most-used variants of them.

[source,java,indent=0]
----
include::../../../src/test/java/snippets/FlatMapTest.java[tags=code]
----

=== How do I merge, concatenate or combine Multis?

You can create instances of `Multi` by concatenating, merging, or combining `Multis` and `Publishers`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/MergeTest.java[tags=code]
----

=== How can I collect / accumulate results?

// TODO

=== How do I chain asynchronous calls?

To chain asynchronous calls, use the `onItem().mapToUni` or `onItem().mapToCompletionStage`:

[source, java, indent=0]
----
include::../../../src/test/java/snippets/HowToChainAsyncTest.java[tags=code]
----

=== How do I recover from failure?

// TODO

=== How do wrap blocking calls?

// TODO

=== How to I control the threads?

// TODO

=== How do I interact with CompletionStage?

// TODO

=== How to I interact with RX Java 2?

// TODO

=== How to I interact with Reactor?

// TODO

=== How do I control the back-pressure?

// TODO

