
= How Do I do _x_?

== How do I transform items?

To transform items synchronously use the `transform` operators:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToTransformTest.java[tags=sync]
----

[NOTE]
====
If your operation throws a _checked exception_, you can use the `io.smallrye.mutiny.unchecked.Unchecked` wrapper to avoid having to catch the exception in the _callback_.

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToTransformTest.java[tags=sync-unchecked]
----
====

You can also transform items asynchronously using the `transformToUni` operator.
In this case, you return a `Uni`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToTransformTest.java[tags=async]
----

If the upstream is a `multi` you can use:

* `transformToUniAndConcatenate` - run the async operation and concatenate the produced items preserving the order from upstream
* `transformToUniAndMerge` - run the async operation and merge the produced items as soon as they are produced.
* `transformToUni` - return an object letting you configure the _flattening_ process (merge or concatenate)

The difference between merge and concatenate is explained in the <<merge-concatenate>> section.
When producing `multis` use:

* `transformToMultiAndConcatenate` - run the async operation and concatenate the items produced by the returned `multis` preserving the order from upstream,
* `transformToMultiAndAndMerge` - run the async operation and merge the items produced by the returned `multis` as soon as they are produced.
* `transformToMulti` - return an object letting you configure the _flattening_ process (merge/concatenate, concurrency, failure collection)

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToTransformTest.java[tags=multi]
----

[NOTE]
.Unchecked
====
Mutiny provides a set of utility classes to handle functions / consumers / suppliers that throw _checked_ exceptions.
`io.smallrye.mutiny.unchecked.Unchecked` wraps code throwing checked exceptions into Java functions/suppliers/consumers.
The `try/catch` is done for you and if an exception occurs, it gets rethrown automatically.

You can add the following import statement to simplify the usage of the provided methods:
`import static io.smallrye.mutiny.unchecked.Unchecked.*;`
====

== How do I filter/select items?

On `Multi`, you may need to filter / select items.
To achieve this, there is a set of methods available in `multi.transform()`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToFilterTest.java[tags=filter]

include::../../../src/test/java/snippets/HowToFilterTest.java[tags=take]

include::../../../src/test/java/snippets/HowToFilterTest.java[tags=skip]

----

You can also drop distinct items or drop repetitions:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToFilterTest.java[tags=distinct]

include::../../../src/test/java/snippets/HowToFilterTest.java[tags=repetition]
----

== Where are my map, flatMap and concatMap methods?

If you are a seasoned reactive developer, you may miss the infamous `map`, `flatMap`, `concatMap` methods.
Mutiny also proposes three methods using the most-used variants of them.

[source,java,indent=0]
----
include::../../../src/test/java/snippets/FlatMapTest.java[tags=rx]
----

Mutiny API is quite different from the _traditional_ reactive eXtensions API.
The equivalent to `map`, `flatMap` and `concatMap` are the following:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/FlatMapTest.java[tags=mutiny]
----

To _peek_ at items, you can use the `invoke` method:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/EventsTest.java[tags=shortcut]
----

`invoke` is a shortcut for `onItem().invoke(...)`.

Mutiny also provides the `call` method for executing an action returning a `Uni`.
This is useful to execute an asynchronous action without modifying incoming item:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/EventsTest.java[tags=call-uni]
----

`call` is a shortcut for `onItem().call(...)`.


.List of the shortcuts offered by the Uni class
|===
|Shortcut | Equivalent

|`uni.map(x -> y)`
|`uni.onItem().transform(x -> y)`

|`uni.flatMap(x -> uni2)`
|`uni.onItem().transformToUni(x -> uni2)`

|`uni.chain(x -> uni2)`
|`uni.onItem().transformToUni(x -> uni2)`

|`uni.then(() -> uni2)`
|`uni.onItem().transformToUni(ignored -> uni2)`

|`uni.invoke(x -> System.out.println(x))`
|`uni.onItem().invoke(x -> System.out.println(x))`

|`uni.call(x -> uni2)`
|`uni.onItem().call(x -> uni2)`

|`uni.eventually(() -> System.out.println("eventually"))`
|`uni.onItemOrFailure().invoke((ignoredItem, ignoredException) -> System.out.println("eventually"))`

|`uni.eventually(() -> uni2)`
|`uni.onItemOrFailure().call((ignoredItem, ignoredException) -> uni2)`
|===


== How do I merge, concatenate or combine Multis?

You can create instances of `Multi` by concatenating, merging, or combining ``Multi``s and ``Publisher``s:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/MergeTest.java[tags=code]
----

== How can I collect / accumulate results?

You can collect the items from a `Multi` using the method proposed by `collectItems()`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/CollectTest.java[tags=code]
----

You can also accumulate results using the `scan` method:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/CollectTest.java[tags=acc]
----

== How do I represent asynchronous calls?

When calling a remote service, or anything asynchronous, you need a way to represent this call.
Most of the time, this should be represented by a `Uni<T>` with `T` the type of result.

For example, a service producing a `String` should be represented as follows:

[source, java]
----
Uni<String> invokeMyService();
----

The returned `Uni` emits the result when the response is available.
If the service invocation fails, the failure is propagated by the `Uni`.

If your service does not produce a result, use `Uni<Void>`:

[source, java]
----
Uni<Void> fireAndForget();
----

In this case, you still know if the invocation fails (you get a failure event) or if the invocation completes successfully (you get a `Void` item (`null`)).

== How do I chain asynchronous calls?

To chain asynchronous calls, use `onItem().transformToUni`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/HowToChainAsyncTest.java[tags=code]
----

== How do I _join_ asynchronous calls?

Joining asynchronous calls, _i.e._ being notified when multiple actions complete, is a common pattern.
With Mutiny, you can achieve this as follows:

[source, java, indent=0]
----
include::../../../src/test/java/snippets/HowToJoinAsyncTest.java[tags=code]
----

In this example, the results are combined into a `Tuple` that contains the different results.

If you have many `Unis` to join, you can use an iterable and a combinator function:

[source, java, indent=0]
----
include::../../../src/test/java/snippets/HowToJoinAsyncTest.java[tags=codeCombinator]
----

The combinator function is invoked with a `List<Object>` as parameter and passes the different results.
This function returns the combined result.

[[merge-concatenate]]
== What's the difference between merge() and concatenate()

Imagine you have a `Multi`, and for each item, you need to call a remote service or execute an asynchronous operation.
To do this, you write the following code:

[source,java]
----
multi
    .onItem().transformToUni(this::asyncService)
    // .concatenate() or .merge() ?
// or
multi
    .onItem().transformToUniAndConcatenate(this::asyncService)
// or
multi
    .onItem().transformToUniAndConcatenateAndMerge(this::asyncService)
----

The difference between these alternatives is about the ordering.
Let's imagine you have the following items: `a`, `b`, `c` and the `asyncService` is just producing the uppercase version (but asynchronously, and you don't know when the result is going to be produced).

`transformToUniAndConcatenate()` preserves the ordering. So, the output will always be `A`, `B`, `C`.
`transformToUniAndMerge()` emits the resulting items as soon as they are available, and so may interleave the items.
The output could be `B`, `A`, `C` if the computation of `b` was faster than for `a`.

`merge` executes the asynchronous operation concurrently, while `concatenate` executes them one by one to preserve the ordering.

`transformToUni` returns an object to configure how the produced items are going to be propagated downstream (flattening).
It lets you choose between two _flattening_ methods: `merge()` and `concatenate()`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/MergeVsConcatenateTest.java[tags=merge]
----

[source,java,indent=0]
----
include::../../../src/test/java/snippets/MergeVsConcatenateTest.java[tags=concatenate]
----

The difference between these alternatives is about the ordering.
Let's imagine you have the following items: `a`, `b`, `c` and the `asyncService` is just producing the uppercase version (but asynchronously, and you don't know when the result is going to be produced).

`concatenate()` preserves the ordering. So, the output will always be `A`, `B`, `C`.
`merge()` emits the resulting items as soon as they are available, and so may interleave the items.
The output could be `B`, `A`, `C` if the computation of `b` was faster than for `a`.

`merge()` executes the asynchronous operation concurrently, while `concatenate()` executes them one by one to preserve the ordering.
With `merge()`, you can also configure the degree of concurrency using: `merge(concurrency)`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/MergeVsConcatenateTest.java[tags=merge-concurrency]
----


[cols="^2,^2",options="header"]
.Differences between the concatenate and merge flattening strategies
|===
2+| Upstream: {a, b, c}

|_concatenate_

    `.transformToUniAndConcatenate(this::asyncService)`
|_merge_

    `.transformToUniAndMerge(this::asyncService)`

|`{A, B, C}`
|`{A, B, C}` or `{B, A, C}` or `{B, C, A}`...

|The downstream items are emitted following the order from the upstream
|The downstream items are emitted as soon as they are received

|===


== How do I recover from failure?

Failures are inherent to software.
So you need to handle them.
By default, they flow in the stream until they reach the final subscriber.
But at any stage you can process the failure and transform or recover from it.

The following snippet shows how you can recover from a failure on a `Uni`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/UniFailureTest.java[tags=code]
----

``Multi``s have the same API letting you recover from failure easily:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/MultiFailureTest.java[tags=code]
----

Note that with `Multi`, a failure cancels the subscription, meaning you will not receive any more items.
The `retry` operator lets you re-subscribe and continue the reception.

== How do I handle `null`?

`null` is only accepted in the `Uni` type.
`uni.onItem().ifNull()` lets you decide what you want to do when the received item is `null`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/UniNullTest.java[tags=code]
----

The symmetric operation is also available with `ifNotNull` which let you handle the case where the item is _not null_:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/UniNullTest.java[tags=code-not-null]
----

IMPORTANT: While supported, emitting `null` should be avoided except for `Uni<Void>`.

== How do I handle timeout?

`Uni` are often used to represent asynchronous operations, like an HTTP call.
So, it's not rare to need to add a timeout on this kind of operation, and recover if the timeout occurs.

This can be done using `Uni.ifNoItem()`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/UniTimeoutTest.java[tags=code]
----

On timeout, you can:

* fail
* recover with a specific item
* continue with another alternative `Uni`

== How do I control the threads?

Except indicated otherwise, the next processor is invoked on the thread emitting the event from upstream.
You can switch to another thread using the `emitOn` operator.
The `emitOn` operator lets you switch the thread used to dispatch (upstream to downstream) events, so items, failure and completion.

[source,java,indent=0]
----
include::../../../src/test/java/snippets/EmitOnTest.java[tags=code]
----

== How do I interact with CompletionStages?

`CompletionStage` and `CompletableFuture` are classes provided by Java to represent asynchronous actions.
However, they are not lazy, and do not follow a _subscription_ patterns.

Mutiny lets you create `Uni` and `Multi` from instances of these classes.
Also, `Uni` offers a way to retrieve the item or the failure as a `CompletableFuture`.

[source,java,indent=0]
----
include::../../../src/test/java/snippets/CompletionStageTest.java[tags=code]
----

== How do I interact with RX Java 2?

Mutiny allows converting Rx Java 2 types to/from Uni and Multi instances.
To enable this feature, add the following dependency to your `CLASSPATH`:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.smallrye.reactive</groupId>
    <artifactId>mutiny-rxjava</artifactId>
    <version>{version}</version>
</dependency>
----

Then, you would need to import:

[source,java]
----
import io.smallrye.mutiny.converters.multi.MultiRxConverters;
import io.smallrye.mutiny.converters.uni.UniRxConverters;
----

To create a `Uni` from RxJava 2 objects, use the following methods:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/RxJavaTest.java[tags=uni-create]
----

When converting a `Completable` or an empty `Maybe` to a `Uni`, the `Uni` receives a `null` item.
Use `onItem().ifNull()` to handle this case.

Note that, when converting an `Observable` or a `Flowable` to a `Uni`, only the first element is requested.
Once received, the underlying subscription is cancelled.

Also note that you can create a `Uni` from a Reactive Streams `Publisher` using `Uni.createFrom().publisher(...)`.

To create Rx Java 2 types from a `Uni`, use the following methods:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/RxJavaTest.java[tags=uni-export]
----

Because `Uni` can emit `null`, the default converter produces a `Single<Optional<T>>`.
You can retrieve a `Single<T>` and fail instead using `toSingle().failOnNull()`.

To create a `Multi` from RxJava 2 objects, use the following methods:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/RxJavaTest.java[tags=multi-create]
----

As for `Uni`, you can create a `Multi` from a Reactive Streams `Publisher` using `Multi.createFrom().publisher(...)`.

You can also create RxJava 2 objects from a `Multi`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/RxJavaTest.java[tags=multi-export]
----

== How do I interact with Reactor?

Mutiny allows converting Project Reactor types to/from `Uni` and `Multi` instances.
To enable this feature, add the following dependency to your `CLASSPATH`:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.smallrye.reactive</groupId>
    <artifactId>mutiny-reactor</artifactId>
    <version>{version}</version>
</dependency>
----

Then, you would need to import:

[source,java]
----
import io.smallrye.mutiny.converters.multi.MultiReactorConverters;
import io.smallrye.mutiny.converters.uni.UniReactorConverters;
----

To create a `Uni` from Reactor objects, use the following methods:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/ReactorTest.java[tags=uni-create]
----

To create Reactor `Flux` and `Mono` instances from a `Uni`, use the following methods:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/ReactorTest.java[tags=uni-export]
----

To create a `Multi` from Reactor objects, use the following methods:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/ReactorTest.java[tags=multi-create]
----

You can also create Reactor objects from a `Multi`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/ReactorTest.java[tags=multi-export]
----

== How do I control the back-pressure?

When a consumer cannot keep up with the pace of a publisher, there is an overflow condition.
By default, it would fail and propagate an exception.

However, you can control how the overflow is handled using the `multi.onOverflow()` method, such as in:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/BackPressureTest.java[tags=code]
----

== How to wrap blocking calls?

It is often the case that a source of data (web service, database...) is synchronous and blocking.
To deal with such sources in your applications, apply the following pattern:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/UniBlockingTest.java[tags=code]
----

Create an `Uni` that will supply the item using a blocking call, here the `invokeRemoteServiceUsingBlockingIO` method.
To avoid blocking the subscriber, use `runSubscriptionOn` which switches the thread and so call `invokeRemoteServiceUsingBlockingIO` on another thread.
Here we pass the default worker thread pool, but you can use your own executor.

Note that `runSubscriptionOn` does not subscribe to the `Uni`.
It specifies the `executor` to use when a subscribe call happens.

Using `runSubscriptionOn` works when the blocking operation happens at subscription time.
But, when you are dealing with `Multi` and need to execute a blocking operation for each item, you need `emitOn`.

While `runSubscriptionOn` runs the subscription on the given executor, `emitOn` configures the executor used to propagate downstream the `item`, `failure` and `completion` events:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/UniBlockingTest.java[tags=code-emitOn]
----

[TIP]
====
You can define a caller thread checker hook by calling `Infrastructure.setCanCallerThreadBeBlockedSupplier(supplier)` to indicate when a blocking operation should not be allowed by Mutiny, resulting in a `IllegalStateException` to be thrown.
====

== emitOn vs. runSubscriptionOn

The `emitOn` and `runSubscriptionOn` are 2 operators influencing on which threads the event are dispatched.
However, they target different types of events and different directions.

`emitOn` takes events coming from upstream (items, completion, failure) and replays them downstream on a thread from the given executor.
Consequently, it affects where the subsequent operators execute (until another `emitOn` is used):

[source,java,indent=0]
----
include::../../../src/test/java/snippets/RunSubscriptionOnTest.java[tags=emitOn]
----

The previous code produces the following sequence:

[plantuml,align=center]
----
include::plantuml/emitOn-sequence.puml[]
----

`runSubscriptionOn` applies to the subscription process.
It requests the upstream to run its subscription (call of the `subscribe` method on its own upstream) on a thread from the given executor:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/RunSubscriptionOnTest.java[tags=runSubscriptionOn]
----

So, if we consider the previous code snippet, it produces the following sequence:

[plantuml,align=center]
----
include::plantuml/runSubscriptionOn-sequence.puml[]
----

== How can I use a Unicast Processor

The `UnicastProcessor` is an implementation of `Multi` that lets you enqueue items in a queue.
The items are then dispatched to the subscriber using the request protocol.
While this pattern is against the idea of back-pressure, it lets you connect sources of data that do not support back-pressure with your subscriber.

In the following example, the `UnicastProcessor` is used by a thread emitting items.
These items are enqueued in the processor and replayed when the subscriber is connected, following the request protocol.

[source,java,indent=0]
----
include::../../../src/test/java/snippets/UnicastProcessorTest.java[tags=code]
----

By default the `UnicastProcessor` uses an unbounded queue.
You can also pass a fixed size queue that would reject the items once full.

== How can I create Uni/Multi from a callback-based API

When dealing with async API using callback, you can create ``Uni``s or ``Multi``s by using _emitters_:

[source, java, indent=0]
----
include::../../../src/test/java/snippets/EmitterTest.java[tags=code]
----

Note that the callback receiving the emitter is called for every subscription.

== How do I create hot streams

In a _cold_ stream, the stream is created when one subscriber subscribes to the stream.
So, if no one subscribes, the actual stream is not created, saving resources (that would be wasted because nobody is interested in the items).

In a _hot_ stream, the stream exists before subscribers subscribe.
The stream emits items even if no subscribers observe the stream.
If there are no subscribers, the items are just dropped.
Subscribers only get items emitted after their subscription, meaning that any previous items would not be received.

To create a hot stream, you can use `io.smallrye.mutiny.operators.multi.processors.BroadcastProcessor` that:

* drops items if no subscribers are present
* forwards items to the set of observing subscribers

[source,java,indent=0]
----
include::../../../src/test/java/snippets/BroadcastProcessorTest.java[tags=code]
----

Note that the `BroadcastProcessor` subscribes to the _hot_ source aggressively and without back-pressure.
However, the `BroadcastProcessor` enforces the back-pressure protocol per subscriber.
If a subscriber is not ready to handle an item emitted by the _hot_ source, an `io.smallrye.mutiny.subscription.BackPressureFailure` is forwarded to this subscriber.

== How do I handle polling?

There are many poll-based API around us.
Sometimes you need to use these APIs to generate a stream from the polled values.
To do this, use the `repeat()` feature:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/PollableSourceTest.java[tags=code]
----

You can also stop the repetition using the `repeat().until()` method which will continue the repetition until the given predicate returns `true`, and/or directly create a `Multi` using `Multi.createBy().repeating()`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/PollableSourceTest.java[tags=code2]
----

== How do I handle pagination?

There are many REST / HTTP APIs using pagination, _i.e._ return only a subset of the results and you need to request the next _page_ to get the next batch.
Each batch contains a list of item(s).
To use this kind of API and generate a continuous stream of items, you need to use the `Multi.createBy().repeating()` function.
However, we need to pass a cursor / state to advance and avoid requesting again and again the same page.
Fortunately, `repeating` provides methods to pass a shared state.
So by combining these methods and `disjoint` you can generate streams from these pages:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/PaginationTest.java[tags=code]
----

First, you create a `Multi` containing the items emitted by the `CompletionStage` supplier and pass a state supplier to progress among the pages.

Then, use `until` to call the paginated API until we have all the items.
At the point we have a stream of list of item such as `["a", "b", "c"], ["d", "e"], []`.
However, we want the following stream: `"a", "b", "c", "d", "e"`.
The `disjoint` method does exactly this.
It gets the items from the lists and passes them downstream:

[plantuml,align=center]
----
include::plantuml/disjoint.puml[]
----

`Multi.createBy().repeating()` lets you choose the number of iterations using:

* `atMost` - exact number of repetitions (or failure happens before reaching that number)
* `until` - the repetition is stopped if the item emitted by the `Uni` **passes** a test (predicate).
It does not propagate the item that did pass the check, and it stops the repetition.
The check verifies if the current item does not contain valid data.
* `whilst` - the repetition is stopped if the item emitted by the `Uni` **does not pass** a test (predicate).
It does propagate the item downstream even if the check does not pass.
However, it stops the repetition.
The test verifies if there is a _next_ batch to be retrieved.

The following code illustrates the usage of `whilst`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/PaginationTest.java[tags=code2]
----

== How do I delay _things_?

You can delay item emission using the `Uni.onItem().delayIt().by(...)` or `Uni.onItem().delayIt().until(...)`.
The first variant delays the emission by a given duration:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/DelayTest.java[tags=delay-by]
----

You can also delay the emission based on an asynchronous result:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/DelayTest.java[tags=delay-until]
----

The item is propagated downstream when the `Uni` returned by the function emits an item (possibly `null`).
If the function emits a failure (or throws an exception), this failure is propagated downstream.

To delay items from a `Multi`, you can use the previously mentioned methods:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/DelayTest.java[tags=delay-multi]
----

Generally, you want to introduce random delays.
You can implement this behavior as follows:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/DelayTest.java[tags=delay-multi-random]
----

== Where do I find the JavaDoc?

The JavaDoc is published https://smallrye.io/smallrye-mutiny/apidocs/[there].

== Default executor and integration

Sometimes, Mutiny needs to execute tasks on other threads, such as monitoring time or delaying actions.
Most operators relying on such capacity let you pass either a `ScheduledExecutorService` or an `ExecutorService`.

Mutiny uses the https://www.oracle.com/technical-resources/articles/java/fork-join.html[fork-join] pool as default executor.
A `ScheduledExecutorService` is also created but delegates the execution of the delayed/scheduled tasks to the default executor.

In the case you want to integrate Mutiny with a thread pool managed by a platform, you can configure it using `Infrastructure.setDefaultExecutor()` method.

== Handling dropped exceptions

There are a few corner cases where Mutiny cannot propagate an exception to a `Uni` or a `Multi` subscriber.
Consider the following example:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/DroppedExceptionTest.java[tags=code]
----

The `onCancellation().call(...)` method is called when the `Uni` subscription is cancelled.
The returned `Uni` is failed with a `IOException`, but since the subscription itself has been cancelled then there is no way to catch the exception.

By default Mutiny reports such dropped exceptions to the standard error stream along with the corresponding stack trace.
You can change how these exceptions are handled using `Infrastructure.setDroppedExceptionHandler`.

The following logs dropped exceptions to a logger:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/DroppedExceptionTest.java[tags=override-handler]
----

== Can I have custom operators?

Yes, but please write operators responsibly!

Both `Uni` and `Multi` support custom operators using the `plug` operator.
Here is an example where we use a custom `Multi` operator that randomly drops items:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/PlugTest.java[tags=plug]
----

with the operator defined as follows:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/PlugTest.java[tags=custom-operator]
----

[WARNING]
====
Custom operators are an advanced feature: when possible please use the existing operators and use helpers such as `stage` to write readable code.
In the case of custom `Multi` operators it is wise to test them against the _Reactive Streams TCK_.
====

== How can I write unit / integration tests?

Mutiny provides subscribers for `Uni` and `Multi` offering helpful assertion methods.
You can use them to test pipelines.

Here is an example to test a `Uni`:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/TestSubscribersTest.java[tags=uni]
----

Testing a `Multi` pipeline is similar:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/TestSubscribersTest.java[tags=multi]
----

The assertions do not just focus on _good_ outcomes, you can also test failures as in:

[source,java,indent=0]
----
include::../../../src/test/java/snippets/TestSubscribersTest.java[tags=failing]
----