---
name: Check pull requests
on:
  pull_request:
    branches-ignore:
      - '1.x'

concurrency:
  group: "check-pull-request-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          { 'version': '17', 'opts': '' },
          { 'version': '21', 'opts': '' },
          { 'version': '25', 'opts': '' }
        ]
    name: Build with Java ${{ matrix.java.version }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        name: set up jdk ${{matrix.java.version}}
        with:
          distribution: temurin
          java-version: ${{matrix.java.version}}
          cache: maven
      - name: Build with Maven
        env:
          MAVEN_OPTS: ${{ matrix.java.opts }}
        run: ./mvnw --no-transfer-progress -s .build/maven-ci-settings.xml -B clean verify -Pcoverage

  conventional-commits:
    runs-on: ubuntu-latest
    name: Check conventional commits
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6
        if: (github.actor!= 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/') == false)

  compatibility:
    runs-on: ubuntu-latest
    name: Compatibility Check
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: 21
          distribution: temurin
          cache: maven
      - name: Compatibility Check
        run: ./mvnw --no-transfer-progress -s .build/maven-ci-settings.xml -pl '!bom' -B install revapi:check@check-compatibility -DskipTests -fae

  documentation:
    runs-on: ubuntu-latest
    name: Documentation build check
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        name: Checkout code
      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        name: Set up Python
        with:
          python-version-file: "documentation/pyproject.toml"
      - name: Other tools setup
        run: sudo snap install yq
      - name: Render docs
        run: |
          cd documentation
          uv sync --all-extras --dev
          uv run mkdocs build
