---
name: Manual website deployment
on:
  workflow_dispatch:
  push:
    branches:
      - "!*"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        name: Checkout code
        with:
          fetch-depth: 0 # fetch all commits and branches for mike to work properly
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        name: Set up Python
        with:
          python-version-file: "documentation/pyproject.toml"
      - name: Other tools setup
        run: |
          git config --global user.name "SmallRye CI"
          git config --global user.email "smallrye@googlegroups.com"
      - name: Render docs and publish
        run: |
          export PROJECT_VERSION=$(cat .github/project.yml | yq eval '.release.current-version' -)
          cd documentation
          uv sync --all-extras --dev
          uv run mkdocs build
          uv run mike deploy --push --update-aliases $PROJECT_VERSION latest
          uv run mike set-default --push latest
